port configure script to Nexenta
git-svn-id: svn://svn.code.sf.net/p/libkqueue/code/trunk@322 fb4e3144-bc1c-4b72-a658-5bcd248dd7f7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,20 @@
 #!/bin/sh
+#
+# Copyright (c) 2009-2010 Mark Heily <mark@heily.com>
+#
+# Permission to use, copy, modify, and distribute this software for any
+# purpose with or without fee is hereby granted, provided that the above
+# copyright notice and this permission notice appear in all copies.
+# 
+# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
+# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
+# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
+# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
+# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
+# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
+# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
+#
+
 
 c_exports="program version target cflags"
 
@@ -88,6 +104,24 @@ check_header() {
    fi
 }
 
+# Determine the path to an executable binary
+check_binary() {
+   id=$1
+   shift
+
+   for path in $*
+   do
+       test -f $path
+       if [ $? = 0 ] ; then
+           eval "$id=\"$path\""
+           return
+       fi
+   done
+
+   echo "not found"
+   return
+}
+
 check_headers() {	 
    for header in $*
    do
@@ -151,11 +185,7 @@ check_target() {
 
 check_compiler() {
     printf "checking for a C compiler.. "
-    if [ "`uname -s`" = "SunOS" ] ; then
-       default_cc="/usr/sfw/bin/gcc"
-    else
-       default_cc="/usr/bin/cc"
-    fi
+    check_binary default_cc "/usr/bin/cc" "/usr/bin/gcc" "/usr/sfw/bin/gcc"
     finalize cc "$default_cc"
     echo "$cc"
 }
@@ -185,7 +215,7 @@ check_linker() {
 
 check_archiver() {
     printf "checking for a suitable archiver.. "
-    if [ "`uname -s`" = "SunOS" ] ; then
+    if [ "`uname -s`" = "SunOS" -a "`uname -v | grep Nexenta`" = "" ] ; then
        default_ar="/usr/sfw/bin/gar"
     else
        default_ar="/usr/bin/ar"
